### ISSUE TITLE
コンセプトを考える

### ISSUE THREAD

**Issue by yuhi-dosei** [yuhi-dosei/spajam2021-pre#5]

**Comment by HiromuYoshida** [comment]
文面振り返ると「概念的ネコを体験する」
ここを少しよりキャッチーだったり、わかりやすい内容へ変えていきたい感

**Comment by HiromuYoshida** [comment]
「様々な環境でペットが飼えない人に向けて、擬似的にネコのいる生活の体験を提供する」
その中で注目するのが、ネコのいたずらやかまって欲しい行動、これらの行動はネコ特有の行動であり、ネコを飼っている人ならあるあるで可愛い行動の一つ。
これらを擬似的に体験することで、ネコとの生活を感じてもらう的な的な

**Comment by HiromuYoshida** [comment]
猫を飼わずして、猫に邪魔をされるたった一つの方法

**Comment by HiromuYoshida** [comment]
猫を飼いたいけど飼えない人が、猫に邪魔されるという行為を体験することができる

**Comment by Atria64** [comment]
LGTM
